"""Scrapy settings for respectful, reproducible academic crawling."""

BOT_NAME = "SEG_FINAL"

SPIDER_MODULES = ["src.crawler.spiders"]
NEWSPIDER_MODULE = "src.crawler.spiders"

ROBOTSTXT_OBEY = True
USER_AGENT = "SEG_FINAL-AcademicSearchProject/1.0"
CONCURRENT_REQUESTS = 4
CONCURRENT_REQUESTS_PER_DOMAIN = 2
DOWNLOAD_DELAY = 1.5
DOWNLOAD_TIMEOUT = 20
RETRY_TIMES = 2

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1.5
AUTOTHROTTLE_MAX_DELAY = 10.0
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0

HTTPCACHE_ENABLED = True
HTTPCACHE_EXPIRATION_SECS = 86400
HTTPCACHE_IGNORE_HTTP_CODES = [403, 429, 500, 502, 503, 504]

ITEM_PIPELINES = {
    "src.crawler.pipelines.ValidateAndDeduplicatePipeline": 300,
}

FEED_EXPORT_ENCODING = "utf-8"
LOG_LEVEL = "INFO"
TELNETCONSOLE_ENABLED = False

